repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        files: python/
    -   id: end-of-file-fixer
        files: python/
    -   id: trailing-whitespace
        files: python/
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        files: python/
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        files: python/
        args: [--config, python/.flake8]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: python/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.0
    hooks:
    -   id: mypy
        files: python/
